### ISSUE TITLE
Sync .rustfmt.toml with parity-common

### ISSUE THREAD

**Issue by emostov** [paritytech/substrate-archive#117]
Enforce a "tools team" rustfmt.

Perhaps the same as `jsonrpsee` (which comes from `parity-common`):

```toml
hard_tabs = true
max_width = 120
use_small_heuristics = "Max"
edition = "2018"
```

_Originally posted by @dvdplm in https://github.com/paritytech/substrate-archive/pull/108#discussion_r511873571_
