### ISSUE TITLE
Store Justifications along with the rest of the block

### ISSUE THREAD

**Issue by insipx** [paritytech/substrate-archive#147]
For one reason or another Justifications aren't stored in the Postgres Database. 

Justification is present on the `SignedBlock` field of `Block` though, so it would be nice to store it if it exists. This requires a new SQL migration that creates a `Justification` column as a `bytea` field. It is possible for justification to be null for a block, so the columns should reflect this.

**Comment by jakehemmerle** [comment]
I'll work on this guy

**Comment by jakehemmerle** [comment]
After trying for an hour or two to get the postgres scripts to work with a docker container, I created a docker-compose.yaml with the URL defaults that makes spinning it up the DB super easy for those (like me) who don't know postgres ins and outs. Is this something worth including in the PR?

```yaml
version: '3'

services:
  # container name is:
  pg-substrate-archive:
    image: 'postgres:latest'
    ports:
      - 5432:5432 # localhost_port:container_port ; don't change container_port
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123 # change me
      POSTGRES_DB: kusama # default db name
```

basically sets up a db instance with user/pass as `postgres` and `123`, `kusama` as the database name, and binds container port 5432 to localhost:5432. Too easy.

docker tl;dr we can stick in the readme:
start it up : `docker-compose up -d`
shut it down: `docker-compose down`
delete it: `docker container stop pg-substrate-archive && docker container rm pg-substrate-archive`
